import { Preset } from '../types';

export const presets: Preset[] = [
  {
    name: "Game of Life (B3/S23)",
    config: {
      type: '2d',
      birth: new Set([3]),
      survival: new Set([2, 3]),
      width: 150,
      height: 150,
      initMode: 'random',
      density: 0.3,
      pattern: null,
      customPattern: null,
      solidBorders: false,
    },
  },
  {
    name: "HighLife (B36/S23)",
    config: {
      type: '2d',
      birth: new Set([3, 6]),
      survival: new Set([2, 3]),
      width: 150,
      height: 150,
      initMode: 'random',
      density: 0.3,
      pattern: null,
      customPattern: null,
      solidBorders: false,
    },
  },
  {
    name: "Seeds (B2/S)",
    config: {
      type: '2d',
      birth: new Set([2]),
      survival: new Set(),
      width: 150,
      height: 150,
      initMode: 'random',
      density: 0.1,
      pattern: null,
      customPattern: null,
      solidBorders: false,
    },
  },
  {
    name: "Day & Night (B3678/S34678)",
    config: {
      type: '2d',
      birth: new Set([3, 6, 7, 8]),
      survival: new Set([3, 4, 6, 7, 8]),
      width: 150,
      height: 150,
      initMode: 'random',
      density: 0.5,
      pattern: null,
      customPattern: null,
      solidBorders: false,
    },
  },
  {
    name: "Diamoeba (B35678/S5678)",
    config: {
      type: '2d',
      birth: new Set([3, 5, 6, 7, 8]),
      survival: new Set([5, 6, 7, 8]),
      width: 150,
      height: 150,
      initMode: 'random',
      density: 0.5,
      pattern: null,
      customPattern: null,
      solidBorders: false,
    },
  },
  {
    name: "Maze (B3/S12345)",
    config: {
      type: '2d',
      birth: new Set([3]),
      survival: new Set([1, 2, 3, 4, 5]),
      width: 150,
      height: 150,
      initMode: 'random',
      density: 0.02,
      pattern: null,
      customPattern: null,
      solidBorders: false,
    },
  },
  {
    name: "Rule 30",
    config: {
      type: '1d',
      rule: 30,
      width: 301,
      initMode: 'center',
      solidBorders: false,
    },
  },
  {
    name: "Rule 90",
    config: {
      type: '1d',
      rule: 90,
      width: 301,
      initMode: 'center',
      solidBorders: false,
    },
  },
  {
    name: "Rule 110",
    config: {
      type: '1d',
      rule: 110,
      width: 301,
      initMode: 'center',
      solidBorders: false,
    },
  },
  {
    name: "Rule 184",
    config: {
      type: '1d',
      rule: 184,
      width: 301,
      initMode: 'random',
      solidBorders: false,
    },
  },
];
